### ISSUE TITLE
Error  pm2 log nodejs v20.11.1

### ISSUE THREAD

**Issue by Trullenque** [soyuka/pidusage#177]
Error: os400 is not supported yet, please open an issue (https://github.com/soyuka/pidusage)
PM2      |     at get (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/pm2/node_modules/pidusage/lib/stats.js:54:21)
PM2      |     at pidusage (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/pm2/node_modules/pidusage/index.js:25:5)
PM2      |     at Object.getMonitorData (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/pm2/lib/God/ActionMethods.js:60:5)
PM2      |     at tasks (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/pm2/lib/Worker.js:149:9)
PM2      |     at Domain.<anonymous> (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/pm2/lib/Worker.js:192:7)
PM2      |     at Domain.run (node:domain:388:15)
PM2      |     at Timeout.wrappedTasks [as _onTimeout] (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/pm2/lib/Worker.js:191:7)
PM2      |     at listOnTimeout (node:internal/timers:573:17)
PM2      |     at process.processTimers (node:internal/timers:514:7)

**Comment by soyuka** [comment]
what was the system ? does it support `ps`?
