### ISSUE TITLE
wmic errored

### ISSUE THREAD

**Issue by Parivalavan** [soyuka/pidusage#38]
This is the message I got in some module that I use. Thought I would bring it here so you may fix this.

Thanks,
Pari

Sun Jun 04 2017 19:46:00 GMT+0530 (India Standard Time) Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Command was "wmic PROCESS 6080 get workingsetsize,usermodetime,kernelmodetime"
 System informations:
 - release: 10.0.15063
 - type Windows_NT
Wmic reported no errors (stderr empty).
Wmic exited with code 0.
Stdout was empty
    at ChildProcess.<anonymous> (D:\WebServer\job_Manager\jobManager\node_modules\pidusage\lib\stats.js:157:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

**Comment by Parivalavan** [comment]
Just found that express-status-monitor plugin is using yours, if that helps

**Comment by soyuka** [comment]
Hmm, this is most likely that the process didn't exist anymore. Therefore, stdout is empty and we had no data to process.

**Comment by soyuka** [comment]
express-status-monitor should try to handle errors (I think I patched this there). You may still have the error log, though it should be handled correctly.

**Comment by utkarshs7** [comment]
This is the response I got for some of the modules, similar to the one raised in this issue. It might be possible that the process may not exist as already mentioned. What is the fix for it?

Thanks,
Utkarsh

Error:
Mon Feb 26 2018 12:08:49 GMT+0530 (India Standard Time) Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Command was "wmic PROCESS 10108 get workingsetsize,usermodetime,kernelmodetime"
 System informations:
 - release: 10.0.16299
 - type Windows_NT
Wmic reported no errors (stderr empty).
Wmic exited with code -4058.
Stdout was empty
    at ChildProcess.<anonymous> (C:\Users\Sagar\Desktop\asg\Node Reference\pidusage-master\lib\stats.js:189:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by soyuka** [comment]
Properly handle the error.
