### ISSUE TITLE
Buffer.alloc issue

### ISSUE THREAD

**Issue by Unitech** [soyuka/pidusage#71]
```
nodejs version: 4.2.6
pm2 3.0.0
npm 6.1.0
```
```
/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:26
buf = Buffer.alloc(SIZE)
^
TypeError: Buffer.alloc is not a function
at readUntilEnd (/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:26:18)
at /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:67:5
at FSReqWrap.oncomplete (fs.js:82:15)
```

https://github.com/Unitech/pm2/issues/3816

**Comment by Unitech** [comment]
Seems that buffer.alloc is only available after node 4.5

**Comment by sandrocsimas** [comment]
@Unitech, I'm getting this error using node version "carbon" (8.11.3).

**Comment by soyuka** [comment]
@sandrocsimas please update pm2 see https://github.com/Unitech/pm2/issues/3827

**Comment by sandrocsimas** [comment]
Thanks @soyuka, I updated yesterday!
