### ISSUE TITLE
Buffer incorrect usage

### ISSUE THREAD

**Issue by encobrain** [soyuka/pidusage#75]
Your lib used in PM2. 
https://github.com/soyuka/pidusage/blob/4adaa1a1bf801a14e6a3c76dba59fda1b56efeda/lib/procfile.js#L27
```
[2018-07-25T15:26:37.579Z] PM2 log: ===============================================================================
[2018-07-25T15:26:37.581Z] PM2 log: --- New PM2 Daemon started ----------------------------------------------------
[2018-07-25T15:26:37.581Z] PM2 log: Time                 : Wed Jul 25 2018 15:26:37 GMT+0300 (EEST)
[2018-07-25T15:26:37.581Z] PM2 log: PM2 version          : 3.0.1
[2018-07-25T15:26:37.581Z] PM2 log: Node.js version      : 8.11.3
[2018-07-25T15:26:37.581Z] PM2 log: Current arch         : x64
[2018-07-25T15:26:37.582Z] PM2 log: PM2 home             : /home/encobrain/.pm2
[2018-07-25T15:26:37.582Z] PM2 log: PM2 PID file         : /home/encobrain/.pm2/pm2.pid
[2018-07-25T15:26:37.582Z] PM2 log: RPC socket file      : /home/encobrain/.pm2/rpc.sock
[2018-07-25T15:26:37.582Z] PM2 log: BUS socket file      : /home/encobrain/.pm2/pub.sock
[2018-07-25T15:26:37.582Z] PM2 log: Application log path : /home/encobrain/.pm2/logs
[2018-07-25T15:26:37.582Z] PM2 log: Process dump file    : /home/encobrain/.pm2/dump.pm2
[2018-07-25T15:26:37.582Z] PM2 log: Concurrent actions   : 2
[2018-07-25T15:26:37.582Z] PM2 log: SIGTERM timeout      : 1600
[2018-07-25T15:26:37.582Z] PM2 log: ===============================================================================
[2018-07-25T15:26:37.618Z] PM2 log: Starting execution sequence in -fork mode- for app name:test id:0
[2018-07-25T15:26:37.625Z] PM2 log: App name:test id:0 online
[2018-07-25T15:26:37.648Z] PM2 log: { Buffer: 
   { [Function: Buffer]
     poolSize: 8192,
     from: [Function],
     alloc: [Function],
     allocUnsafe: [Function],
     allocUnsafeSlow: [Function],
     isBuffer: [Function: isBuffer],
     compare: [Function: compare],
     isEncoding: [Function],
     concat: [Function],
     byteLength: [Function: byteLength],
     [Symbol(node.isEncoding)]: [Function] },
  SlowBuffer: [Function: SlowBuffer],
  INSPECT_MAX_BYTES: 50,
  kMaxLength: 2147483647,
  constants: { MAX_LENGTH: 2147483647, MAX_STRING_LENGTH: 1073741799 },
  kStringMaxLength: 1073741799,
  transcode: [Function: transcode] }
[2018-07-25T15:26:37.648Z] PM2 log: ===============================================================================
[2018-07-25T15:26:37.648Z] PM2 log: --- PM2 global error caught ---------------------------------------------------
[2018-07-25T15:26:37.649Z] PM2 log: Time                 : Wed Jul 25 2018 15:26:37 GMT+0300 (EEST)
[2018-07-25T15:26:37.649Z] PM2 error: Buffer.alloc is not a function
[2018-07-25T15:26:37.649Z] PM2 error: TypeError: Buffer.alloc is not a function
    at readUntilEnd (/home/encobrain/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:32:18)
    at /home/encobrain/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:73:5
    at FSReqWrap.oncomplete (fs.js:135:15)
[2018-07-25T15:26:37.649Z] PM2 log: ===============================================================================
[2018-07-25T15:26:37.650Z] PM2 error: [PM2] Resurrecting PM2
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[2018-07-25T15:26:37.819Z] PM2 log: { Buffer: 
   { [Function: Buffer]
     poolSize: 8192,
     from: [Function],
     alloc: [Function],
     allocUnsafe: [Function],
     allocUnsafeSlow: [Function],
     isBuffer: [Function: isBuffer],
     compare: [Function: compare],
     isEncoding: [Function],
     concat: [Function],
     byteLength: [Function: byteLength],
     [Symbol(node.isEncoding)]: [Function] },
  SlowBuffer: [Function: SlowBuffer],
  INSPECT_MAX_BYTES: 50,
  kMaxLength: 2147483647,
  constants: { MAX_LENGTH: 2147483647, MAX_STRING_LENGTH: 1073741799 },
  kStringMaxLength: 1073741799,
  transcode: [Function: transcode] }
/home/encobrain/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:32
    buf = Buffer.alloc(SIZE)
                 ^

TypeError: Buffer.alloc is not a function
    at readUntilEnd (/home/encobrain/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:32:18)
    at /home/encobrain/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:73:5
    at FSReqWrap.oncomplete (fs.js:135:15)
```
error here:

**Comment by soyuka** [comment]
Update pm2 this has been fixed

**Comment by encobrain** [comment]
What a quick fix! Yesterday was bug :+1: ))))

**Comment by soyuka** [comment]
FYI there is a 3h gap with a buggy version of pidusage due to a mispublish. Everything should be back to normal now.
